### ISSUE TITLE
can you discuss the best practice of creating naming a branch 

### ISSUE THREAD

**Issue by iStryker** [githubteacher/github-for-developers-sept-2015#380] opened 2015-09-29 17:30 UTC
What is the best practice for naming a branch

Correct me if I am wrong
It is best to create an issue about X.  Create a branch with the issue # and small description.

**Comment by jaw6** [comment] 2015-09-29 17:35
@iStryker: typically, we recommend giving your branch a name that meaningfully describes the feature you're working on. "Meaningfully" can be very context-dependent, though: in some environments, it might be best to name branches after specific bugs or stories (eg, `bug123` or `storyIDHERE`), but I, personally, find that a little too abstract. I tend to prefer more descriptive names, like `paypal_payments` or `refactor_class` or `update_home_page`. In practice, if you use short-lived branches, it's rare to have problems coming up with a good, descriptive name.

**Comment by iStryker** [comment] 2015-09-29 17:50
@jaw6 -  Isn't creating a branch #111-refactor_class better than refactor_class?   That way ppl know what you are working on.  That way someone does not create refactor_class branch,  and someone else creates rewrite_function_x,  while they are the same thing

@githubteacher mention a good point about creating a pull request right away, with reference, they you cannot get confuse.

Inaddition, when you view you network, to me it makes more sense when you tag issue number with branch

**Comment by jaw6** [comment] 2015-09-29 18:44
> Isn't creating a branch #111-refactor_class better than refactor_class? That way ppl know what you are working on.

@iStryker a naming convention like that can be helpful -- no doubt -- but I find it's best to use descriptive branch names and **link** the pull request to the associated bug/issue. My experience as a developer has been that links are a richer medium -- among other things, the bi-direction links between issues & pull requests display the status of the linked pull request on the associated issue, meaning that the issue reporter has a indicator that the issue is being worked on (and, eventually, that the fix has been merged, or not).

Another potential concern with the naming convention you suggest is if a branch / pull request is intended to address more than one associated bug/issue. It's _best_ to focus on one issue at a time, but, as a developer, there will be times when a "clean up" branch resolves more than one bug all at one go.

Again, there's nothing wrong with a branch naming convention, but it's been my experience that it's often better to be descriptive and use links to associate the pull request with any associated issues.

**Closed as completed by jaw6** 2015-09-29 18:44 UTC
Labels: answered
